name: Hello world

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    name: Hello World-2
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello to Every One
        run: echo "Hello, everyone!"

